name: "CI"
on:
  # pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    # - run: gunzip < neuron-full-closure.export.gz | nix-store --import
    # - name: Build site
    #   run: /nix/store/pz08vmgv1y1vlvx0jfjwdwjvhs06246d-neuron-0.5.5.1/bin/neuron -d . rib

    # # This also runs nix-build.
    - uses: cachix/cachix-action@v6
      with:
        name: srid
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # This builds neuron, as well as run tests
    - run: nix-env -if "https://github.com/srid/neuron/archive/736107f8dd12ed514b6956c9e938437b5bd5fa49.tar.gz"
    - run: /nix/var/nix/profiles/default/bin/nix-store -qR $(which neuron)
    - name: Build site
      run: neuron -d . rib
    # - name: push
    #   uses: github-actions-x/commit@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     push_branch: 'master'
    #     add: ...
    #     commit_message: 'publish'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
    - run: git status
